# ClusterIssuer for home CA - applied after cert-manager CRDs exist
# Retries until cert-manager.io/v1 ClusterIssuer CRD is available
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: gitops-veil
  path: ./issuer
  prune: true
  wait: true
