apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 10m
  install:
    createNamespace: true
  targetNamespace: object-store
  chart:
    spec:
      chart: minio
      version: 17.0.21
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  values:
    # Use Bitnami Legacy repositories due to catalog changes
    image:
      registry: docker.io
      repository: bitnamilegacy/minio
    # Distributed mode; try 6 pods × 1 drive (EC(4,2) requires >=4, even)
    mode: distributed
    statefulset:
      replicaCount: 6
      drivesPerNode: 1
    resourcesPreset: medium

    # COLD START: Create the Secret "minio-root" in namespace object-store with
    # keys "root-user" and "root-password" before first deploy. Example:
    #   kubectl create ns object-store || true
    #   kubectl -n object-store create secret generic minio-root \
    #     --from-literal=root-user="minioadmin" \
    #     --from-literal=root-password="<change-me>"
    auth:
      existingSecret: minio-root

    persistence:
      enabled: true
      size: 125Gi
      storageClass: local-path

    # Prefer spreading but don't block scheduling (servers only)

    service:
      type: ClusterIP
    # Console service type under console.service

    # Expose API and Console via ingress-nginx at 192.168.0.220
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: s3.veil.home.arpa
      path: /
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
      tls: false

    console:
      image:
        registry: docker.io
        repository: bitnamilegacy/minio-object-browser
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: nginx
        hostname: s3-console.veil.home.arpa
        path: /
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/proxy-buffering: "off"
        tls: false
      resourcesPreset: small
