# Docker Registry - in-cluster container image registry
# Uses MinIO S3 backend for storage
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  targetNamespace: registry
  chart:
    spec:
      chart: docker-registry
      version: 2.2.3
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
  values:
    # Storage: MinIO S3 backend
    # COLD START: Create bucket "registry" in MinIO before first deploy
    # COLD START: Create secret "registry-s3" with MinIO credentials:
    #   kubectl create ns registry
    #   kubectl -n registry create secret generic registry-s3 \
    #     --from-literal=s3AccessKey="minioadmin" \
    #     --from-literal=s3SecretKey="<minio-root-password>"
    storage: s3
    secrets:
      s3:
        secretRef: registry-s3
    s3:
      region: us-east-1
      bucket: registry
      regionEndpoint: http://minio.object-store.svc.cluster.local:9000
      secure: false
      encrypt: false

    # Ingress with TLS
    ingress:
      enabled: true
      className: nginx
      hosts:
        - registry.veil.home.arpa
      annotations:
        cert-manager.io/cluster-issuer: "home-ca"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      tls:
        - secretName: registry-tls
          hosts:
            - registry.veil.home.arpa

    # Resources for homelab
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 256Mi
