apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: flux-system
spec:
  interval: 10m
  timeout: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  targetNamespace: gpu-operator
  chart:
    spec:
      chart: gpu-operator
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
  values:
    # NixOS manages the NVIDIA driver on the host
    driver:
      enabled: false

    # NixOS provides nvidia-container-toolkit via hardware.nvidia-container-toolkit
    toolkit:
      enabled: false

    # Device plugin discovers GPUs and exposes them to k8s
    devicePlugin:
      enabled: true

    # DCGM exporter for Prometheus metrics
    dcgmExporter:
      enabled: true
      serviceMonitor:
        enabled: true

    # GPU feature discovery for node labels
    gfd:
      enabled: true

    # Node feature discovery (detects hardware capabilities)
    nfd:
      enabled: true

    # MIG manager not needed for consumer GPUs
    migManager:
      enabled: false

    # Sandbox workloads not needed
    sandboxWorkloads:
      enabled: false

    # vGPU not applicable
    vgpuManager:
      driver:
        enabled: false

    # vfio-manager not needed
    vfioManager:
      enabled: false

    # Only schedule GPU operator components on nodes with NVIDIA GPUs
    daemonsets:
      labels:
        gpu: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
