apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 10m
  install:
    createNamespace: true
  targetNamespace: object-store
  chart:
    spec:
      chart: minio
      # Use a stable Bitnami chart version; adjust as needed
      version: 14.7.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Distributed mode across 3 replicas with 2 drives each => 6 drives total
    # MinIO will apply EC(4,2) automatically for 6 drives
    mode: distributed
    replicas: 3
    drivesPerNode: 2

    # COLD START: Create the Secret "minio-root" in namespace object-store with
    # keys "root-user" and "root-password" before first deploy. Example:
    #   kubectl create ns object-store || true
    #   kubectl -n object-store create secret generic minio-root \
    #     --from-literal=root-user="minioadmin" \
    #     --from-literal=root-password="<change-me>"
    auth:
      existingSecret: minio-root

    persistence:
      enabled: true
      size: 125Gi
      storageClass: local-path

    # Spread pods across nodes; prefer one per node
    podAntiAffinityPreset: hard
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: minio

    service:
      type: ClusterIP
    consoleService:
      type: ClusterIP

    # Expose API and Console via ingress-nginx at 192.168.0.220
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: s3.veil.home.arpa
      path: /
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
      tls: []

    consoleIngress:
      enabled: true
      ingressClassName: nginx
      hostname: s3-console.veil.home.arpa
      path: /
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
      tls: []
