apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  install:
    createNamespace: true
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 66.3.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    defaultRules:
      create: true
      rules:
        alertmanager: true
        etcd: true
        general: true
        kubeApiserver: true
        kubeControllerManager: true
        kubeScheduler: true
        kubeStateMetrics: true
        kubelet: true
        node: true
        prometheus: true
    kubeEtcd:
      enabled: true
    prometheus:
      prometheusSpec:
        additionalScrapeConfigsSecret:
          enabled: true
          name: additional-scrape-configs
          key: additional-scrape-configs.yaml
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.veil.home.arpa
        paths:
          - /
        pathType: Prefix
    grafana:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.veil.home.arpa
        path: /
        pathType: Prefix
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          searchNamespace: ALL
      dashboards: {}
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - alertmanager.veil.home.arpa
        paths:
          - /
        pathType: Prefix
