apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  install:
    createNamespace: true
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 66.3.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.veil.home.arpa
        path: /
        pathType: Prefix
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - alertmanager.veil.home.arpa
        paths:
          - /
        pathType: Prefix
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.veil.home.arpa
        paths:
          - /
        pathType: Prefix
