{ config, pkgs, ... }:

{
  boot.kernelModules = [ "nct6775" "jc42" "lm75" ];

  environment.systemPackages = with pkgs; [
    # May need to run `sudo sensors-detect` to configure sensors
    # May need to run `sudo pwmconfig` to configure fan control
    lm_sensors
  ];

  # skaia:
  #   has the following sensors:
  #     hwmon3/temp1_input (CPU via K10Temp Tctl)
  #     hwmon2/temp2_input (CPU via NCT6798)
  #   has the following fans under PWM control:
  #     hwmon2/fan2_input (rear)
  #     hwmon2/fan3_input (???)
  #     hwmon2/fan5_input (bottom)
  #     hwmon2/fan7_input (???)

  hardware.fancontrol = {
    enable = true;
    config = ''
      # Configuration file generated by pwmconfig, changes will be lost
      INTERVAL=10
      DEVPATH=hwmon2=devices/platform/nct6775.656 hwmon3=devices/pci0000:00/0000:00:18.3
      DEVNAME=hwmon2=nct6798 hwmon3=k10temp
      FCTEMPS=hwmon2/pwm7=hwmon2/temp2_input hwmon2/pwm5=hwmon2/temp2_input hwmon2/pwm3=hwmon2/temp2_input hwmon2/pwm2=hwmon2/temp2_input
      FCFANS=hwmon2/pwm7=hwmon2/fan7_input hwmon2/pwm5=hwmon2/fan5_input hwmon2/pwm3=hwmon2/fan3_input hwmon2/pwm2=hwmon2/fan2_input
      MINTEMP=hwmon2/pwm7=30 hwmon2/pwm5=35 hwmon2/pwm3=30 hwmon2/pwm2=40
      MAXTEMP=hwmon2/pwm7=50 hwmon2/pwm5=65 hwmon2/pwm3=60 hwmon2/pwm2=70
      MINSTART=hwmon2/pwm7=135 hwmon2/pwm5=135 hwmon2/pwm3=135 hwmon2/pwm2=120
      MINSTOP=hwmon2/pwm7=40 hwmon2/pwm5=40 hwmon2/pwm3=40 hwmon2/pwm2=40
    '';
  };
}

# COLD START: This host may require manual firmware/module setup and sensor/fan configuration. See docs/COLD-START.md for details.
