{ config, pkgs, ... }:

{
  boot.kernelModules = [ "nct6775" ];

  environment.systemPackages = with pkgs; [
    # May need to run `sudo sensors-detect` to configure sensors
    # May need to run `sudo pwmconfig` to configure fan control
    lm_sensors
  ];

  # skaia has the following fans under PWM control:
  #   hwmon14/fan2_input (rear)
  #   hwmon14/fan3_input (???)
  #   hwmon14/fan5_input (???)
  #   hwmon14/fan7_input (???)

  hardware.fancontrol = {
    enable = true;
    config = ''
      # Configuration file generated by pwmconfig, changes will be lost
      INTERVAL=5
      DEVPATH=hwmon14=devices/platform/nct6775.656 hwmon2=devices/pci0000:00/0000:00:18.3
      DEVNAME=hwmon14=nct6798 hwmon2=k10temp
      FCTEMPS=hwmon14/pwm7=hwmon2/temp1_input hwmon14/pwm5=hwmon2/temp1_input hwmon14/pwm3=hwmon2/temp1_input hwmon14/pwm2=hwmon2/temp1_input
      FCFANS=hwmon14/pwm7=hwmon14/fan7_input hwmon14/pwm5=hwmon14/fan5_input hwmon14/pwm3=hwmon14/fan3_input hwmon14/pwm2=hwmon14/fan2_input
      MINTEMP=hwmon14/pwm7=42 hwmon14/pwm5=42 hwmon14/pwm3=42 hwmon14/pwm2=42
      MAXTEMP=hwmon14/pwm7=60 hwmon14/pwm5=60 hwmon14/pwm3=60 hwmon14/pwm2=85
      MINSTART=hwmon14/pwm7=150 hwmon14/pwm5=150 hwmon14/pwm3=150 hwmon14/pwm2=165
      MINSTOP=hwmon14/pwm7=40 hwmon14/pwm5=40 hwmon14/pwm3=40 hwmon14/pwm2=40
    '';
  };
}
