{ config, pkgs, ... }:

{
  boot.kernelModules = [ "nct6775" "jc42" "lm75" ];

  environment.systemPackages = with pkgs; [
    # May need to run `sudo sensors-detect` to configure sensors
    # May need to run `sudo pwmconfig` to configure fan control
    lm_sensors
  ];

  # skaia:
  #   has the following sensors:
  #     hwmon2/temp1_input (CPU via K10Temp Tctl)
  #     hwmon14/temp2_input (CPU via NCT6798)
  #   has the following fans under PWM control:
  #     hwmon14/fan2_input (rear)
  #     hwmon14/fan3_input (???)
  #     hwmon14/fan5_input (bottom)
  #     hwmon14/fan7_input (???)

  hardware.fancontrol = {
    enable = true;
    config = ''
      # Configuration file generated by pwmconfig, changes will be lost
      INTERVAL=10
      DEVPATH=hwmon14=devices/platform/nct6775.656 hwmon2=devices/pci0000:00/0000:00:18.3
      DEVNAME=hwmon14=nct6798 hwmon2=k10temp
      FCTEMPS=hwmon14/pwm7=hwmon14/temp2_input hwmon14/pwm5=hwmon14/temp2_input hwmon14/pwm3=hwmon14/temp2_input hwmon14/pwm2=hwmon14/temp2_input
      FCFANS=hwmon14/pwm7=hwmon14/fan7_input hwmon14/pwm5=hwmon14/fan5_input hwmon14/pwm3=hwmon14/fan3_input hwmon14/pwm2=hwmon14/fan2_input
      MINTEMP=hwmon14/pwm7=30 hwmon14/pwm5=35 hwmon14/pwm3=30 hwmon14/pwm2=40
      MAXTEMP=hwmon14/pwm7=50 hwmon14/pwm5=65 hwmon14/pwm3=60 hwmon14/pwm2=70
      MINSTART=hwmon14/pwm7=135 hwmon14/pwm5=135 hwmon14/pwm3=135 hwmon14/pwm2=120
      MINSTOP=hwmon14/pwm7=40 hwmon14/pwm5=40 hwmon14/pwm3=40 hwmon14/pwm2=40
    '';
  };
}
