{
  config,
  lib,
  pkgs,
  ...
}:

let
  # Hostnames the ntfy iOS app needs to resolve for FCM/APNs. StevenBlack
  # currently NXDOMAINs firebaselogging-pa.googleapis.com, which silently
  # kills iOS push on LAN clients using this resolver. Keep the rest of
  # the set even if a name is not currently blocked, so a future list
  # update cannot break push again.
  fcmAllowlist = [
    "firebaselogging-pa.googleapis.com"
    "firebaselogging.googleapis.com"
    "firebaseinstallations.googleapis.com"
    "fcm.googleapis.com"
    "fcmtoken.googleapis.com"
    "fcmregistrations.googleapis.com"
    "device-provisioning.googleapis.com"
    "android.apis.google.com"
  ];

  # Included *after* the generated RPZ file. `transparent` with no local
  # data forwards to upstream resolvers, overriding always_nxdomain for
  # the same name as long as this file is loaded last.
  allowlistConf = pkgs.writeText "unbound-rpz-allowlist.conf" (
    lib.concatMapStrings (d: ''
      local-zone: "${d}." transparent
    '') fcmAllowlist
  );

  allowlistPattern = lib.concatMapStringsSep "|" (
    d: lib.replaceStrings [ "." ] [ "\\." ] d
  ) fcmAllowlist;

  updateScript = pkgs.writeShellScript "update-unbound-rpz" ''
    		set -euo pipefail
    		WORKDIR=/var/lib/unbound
    		OUTFILE="$WORKDIR/rpz-local-zones.conf"
    		TMPFILE="$OUTFILE.tmp"
    		mkdir -p "$WORKDIR"

    		echo "# Generated by unbound-rpz-update $(date -u +%FT%TZ)" > "$TMPFILE"

    		# Resolve raw.githubusercontent.com via a public resolver to avoid local DNS deps
    		RESOLVED_IP=$(${pkgs.dnsutils}/bin/dig +short @1.1.1.1 raw.githubusercontent.com A | ${pkgs.coreutils}/bin/head -n1 || true)
    		if [ -z "$RESOLVED_IP" ]; then
    			echo "[unbound-rpz] WARN: Failed to resolve raw.githubusercontent.com via 1.1.1.1; keeping existing RPZ" >&2
    			# Ensure file exists and exit successfully to avoid blocking Unbound
    			: > "$TMPFILE"
    			${pkgs.coreutils}/bin/mv -f "$TMPFILE" "$OUTFILE"
    			exit 0
    		fi

    		# Fetch StevenBlack hosts list with explicit resolved IP and retries
    		if ! ${pkgs.curl}/bin/curl -fsSL --retry 5 --retry-delay 2 \
    			--resolve raw.githubusercontent.com:443:$RESOLVED_IP \
    			https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts \
    			| ${pkgs.gnugrep}/bin/grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\s' \
    			| ${pkgs.gawk}/bin/awk '{print $2}' \
    			| ${pkgs.gnused}/bin/sed -E 's/#.*$//' \
    			| ${pkgs.gnugrep}/bin/grep -Ev '^(localhost|localhost\.|localdomain|broadcasthost)$' \
    			| ${pkgs.gnugrep}/bin/grep -Ev '\.local$' \
    			| ${pkgs.gnugrep}/bin/grep -Ev '^(${allowlistPattern})$' \
    			| ${pkgs.coreutils}/bin/sort -u \
    			| ${pkgs.gawk}/bin/awk '{ printf("local-zone: \"%s\" always_nxdomain\n", $0) }' \
    			>> "$TMPFILE"; then
    			echo "[unbound-rpz] WARN: Fetch failed; keeping existing RPZ" >&2
    			: > "$TMPFILE"
    		fi

    		${pkgs.coreutils}/bin/mv -f "$TMPFILE" "$OUTFILE"
    		${pkgs.coreutils}/bin/chmod 0644 "$OUTFILE"

    		# Daily timer updates the file on disk; Unbound only rereads it
    		# on reload. Skip when Unbound is not running yet (boot).
    		#
    		# Unbound is After= this unit. A synchronous reload deadlocks
    		# nixos-rebuild switch: Unbound waits for us to finish, we wait
    		# for Unbound to reload. Skip if a job is already queued
    		# (switch-to-configuration will reload Unbound itself).
    		# Otherwise queue the reload and return.
    		if ${pkgs.systemd}/bin/systemctl is-active --quiet unbound.service; then
    			if ${pkgs.systemd}/bin/systemctl list-jobs --full --no-legend \
    				| ${pkgs.gnugrep}/bin/grep -F -q 'unbound.service'; then
    				echo "[unbound-rpz] unbound already has a systemd job; skip reload" >&2
    			else
    				${pkgs.systemd}/bin/systemctl reload --no-block unbound.service \
    					|| echo "[unbound-rpz] WARN: unbound reload failed" >&2
    			fi
    		fi
    	'';
in
{
  systemd = {
    services = {
      unbound-rpz-update = {
        description = "Update Unbound RPZ (local-zone) blocklist";
        serviceConfig = {
          Type = "oneshot";
          ExecStart = updateScript;
          User = "root";
          Group = "root";
          PermissionsStartOnly = true;
        };
        wants = [ "network-online.target" ];
        after = [ "network-online.target" ];
        wantedBy = [ "multi-user.target" ];
      };

      # Ensure Unbound consumes the generated RPZ and does not get blocked if update fails
      unbound = {
        after = [ "unbound-rpz-update.service" ];
        wants = [ "unbound-rpz-update.service" ];
      };
    };

    timers = {
      unbound-rpz-update = {
        wantedBy = [ "timers.target" ];
        timerConfig = {
          OnBootSec = "10min";
          OnUnitActiveSec = "24h";
          Unit = "unbound-rpz-update.service";
        };
      };
    };
  };

  # RPZ first, allowlist second so transparent zones win for FCM hosts.
  services.unbound.settings.server.include = [
    "/var/lib/unbound/rpz-local-zones.conf"
    "${allowlistConf}"
  ];
}
