{ config, lib, pkgs, ... }:

let
  updateScript = pkgs.writeShellScript "update-unbound-rpz" ''
    		set -euo pipefail
    		WORKDIR=/var/lib/unbound
    		OUTFILE="$WORKDIR/rpz-local-zones.conf"
    		TMPFILE="$OUTFILE.tmp"
    		mkdir -p "$WORKDIR"

    		echo "# Generated by unbound-rpz-update $(date -u +%FT%TZ)" > "$TMPFILE"

    		# Resolve raw.githubusercontent.com via a public resolver to avoid local DNS deps
    		RESOLVED_IP=$(${pkgs.dnsutils}/bin/dig +short @1.1.1.1 raw.githubusercontent.com A | ${pkgs.coreutils}/bin/head -n1 || true)
    		if [ -z "$RESOLVED_IP" ]; then
    			echo "[unbound-rpz] WARN: Failed to resolve raw.githubusercontent.com via 1.1.1.1; keeping existing RPZ" >&2
    			# Ensure file exists and exit successfully to avoid blocking Unbound
    			: > "$TMPFILE"
    			${pkgs.coreutils}/bin/mv -f "$TMPFILE" "$OUTFILE"
    			exit 0
    		fi

    		# Fetch StevenBlack hosts list with explicit resolved IP and retries
    		if ! ${pkgs.curl}/bin/curl -fsSL --retry 5 --retry-delay 2 \
    			--resolve raw.githubusercontent.com:443:$RESOLVED_IP \
    			https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts \
    			| ${pkgs.gnugrep}/bin/grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\s' \
    			| ${pkgs.gawk}/bin/awk '{print $2}' \
    			| ${pkgs.gnused}/bin/sed -E 's/#.*$//' \
    			| ${pkgs.gnugrep}/bin/grep -Ev '^(localhost|localhost\.|localdomain|broadcasthost)$' \
    			| ${pkgs.gnugrep}/bin/grep -Ev '\.local$' \
    			| ${pkgs.coreutils}/bin/sort -u \
    			| ${pkgs.gawk}/bin/awk '{ printf("local-zone: \"%s\" always_nxdomain\n", $0) }' \
    			>> "$TMPFILE"; then
    			echo "[unbound-rpz] WARN: Fetch failed; keeping existing RPZ" >&2
    			: > "$TMPFILE"
    		fi

    		${pkgs.coreutils}/bin/mv -f "$TMPFILE" "$OUTFILE"
    		${pkgs.coreutils}/bin/chmod 0644 "$OUTFILE"
    	'';
in
{
  systemd = {
    services = {
      unbound-rpz-update = {
        description = "Update Unbound RPZ (local-zone) blocklist";
        serviceConfig = {
          Type = "oneshot";
          ExecStart = updateScript;
          User = "root";
          Group = "root";
          PermissionsStartOnly = true;
        };
        wants = [ "network-online.target" ];
        after = [ "network-online.target" ];
        wantedBy = [ "multi-user.target" ];
      };

      # Ensure Unbound consumes the generated RPZ and does not get blocked if update fails
      unbound = {
        after = [ "unbound-rpz-update.service" ];
        wants = [ "unbound-rpz-update.service" ];
      };
    };

    timers = {
      unbound-rpz-update = {
        wantedBy = [ "timers.target" ];
        timerConfig = {
          OnBootSec = "10min";
          OnUnitActiveSec = "24h";
          Unit = "unbound-rpz-update.service";
        };
      };
    };
  };

  # Add include for the generated RPZ file
  services.unbound.settings.server.include = "/var/lib/unbound/rpz-local-zones.conf";
}
