apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 10m
  install:
    createNamespace: true
  chart:
    spec:
      chart: metallb
      version: 0.14.8
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
